export enum NOTIFICATION_TYPE {
  USER_CREATED = "USER_CREATED",
  USER_UPDATED = "USER_UPDATED",
  ACCOUNT_ADD_FOUNDS = "ACCOUNT_ADD_FOUNDS",
  ACCOUNT_SEND_MONEY = "ACCOUNT_SEND_MONEY",
  ACCOUNT_GET_MONEY = "ACCOUNT_RECEIVE_MONEY",
}
