version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongodb_container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: jared
      MONGO_INITDB_ROOT_PASSWORD: jared123

volumes:
  mongo_data:
